#ifndef HOME_ROY_PUBLIC_GOOGLEADSLISTENER_RBK_MISC_CONTROLFLOWMACRO_H
#define HOME_ROY_PUBLIC_GOOGLEADSLISTENER_RBK_MISC_CONTROLFLOWMACRO_H

#define BREAK_IF_TRUE(Func) \
	if (Func) {         \
		break;      \
	}

#define RETURN_IF_TRUE(func) \
	if (func) {          \
		return;      \
	}

#endif // HOME_ROY_PUBLIC_GOOGLEADSLISTENER_RBK_MISC_CONTROLFLOWMACRO_H
