#ifndef HOME_ROY_PUBLIC_GOOGLEADSLISTENER_RBK_MISC_TYPES_H
#define HOME_ROY_PUBLIC_GOOGLEADSLISTENER_RBK_MISC_TYPES_H
#include <cstdint>

using u64 = uint64_t;
using i64 = int64_t;

#endif // HOME_ROY_PUBLIC_GOOGLEADSLISTENER_RBK_MISC_TYPES_H
