#ifndef HOME_ROY_PUBLIC_DIGITALSPINE_RBK_MINMYSQL_CHECKSCHEMA_CHECKSCHEMACONF_H
#define HOME_ROY_PUBLIC_DIGITALSPINE_RBK_MINMYSQL_CHECKSCHEMA_CHECKSCHEMACONF_H

struct DBMaintainance {
	bool checkCongruency = true;
	bool refreshDBSchema = false;
};

#endif // HOME_ROY_PUBLIC_DIGITALSPINE_RBK_MINMYSQL_CHECKSCHEMA_CHECKSCHEMACONF_H
