#ifndef HOME_ROY_PUBLIC_DIGITALSPINE_RBK_MINMYSQL_CHECKSCHEMA_CHECKSCHEMADESCRIBE_H
#define HOME_ROY_PUBLIC_DIGITALSPINE_RBK_MINMYSQL_CHECKSCHEMA_CHECKSCHEMADESCRIBE_H

#include "CheckSchemaConf.h"
#include <boost/describe.hpp>

BOOST_DESCRIBE_STRUCT(DBMaintainance, (), (checkCongruency, refreshDBSchema))

#endif // HOME_ROY_PUBLIC_DIGITALSPINE_RBK_MINMYSQL_CHECKSCHEMA_CHECKSCHEMADESCRIBE_H
