#ifndef TMP_QTCREATOR_MCCAVM_CLANGTOOLS_VFSO_SEEXJX_MIME_H_AUTO
#define TMP_QTCREATOR_MCCAVM_CLANGTOOLS_VFSO_SEEXJX_MIME_H_AUTO

#include <string_view>

std::string_view getMimeType(std::string_view file);

#endif // TMP_QTCREATOR_MCCAVM_CLANGTOOLS_VFSO_SEEXJX_MIME_H_AUTO
